[{
    label: "文件",
    items: [{
        label: "选择图片",
        keyEquivalent: "O",
        onSelect: doBrowseImg
    }, {
        label: "读取定义文件",
        keyEquivalent: "O",
        shiftKey: true,
        onSelect: doBrowseXml
    }, {
        type: "separator"
    }, {
        label: "保存当前定义",
        keyEquivalent: "S",
        onSelect: doSave
    }]
}, {
    label: "图层",
    items: [{
        label: "显示｜隐藏“当前层信息”",
        keyEquivalent: "N",
        onSelect: showNonceDiv
    }, {
        label: "显示｜隐藏“所有层信息”",
        keyEquivalent: "N",
        shiftKey: true,
        name: "allDiv",
        onSelect: menuOpenWin
    }]
}, {
    label: "操作",
    items: [{
        label: "刷新图片",
        toggled: "true",
        onSelect: refreshPic
    }, {
        type: "separator"
    },{
        label: "新建层时显示“当前层信息”",
        type: "check",
		name: "show_new",
        toggled: "true",
        onSelect: setShowDiv
    }, {
        label: "选中层时显示“当前层信息”",
        type: "check",
		name: "show_nonce",
        toggled: "true",
        onSelect: setShowDiv
    }, {
        type: "separator"
    }, {
        label: "显示｜隐藏“区定义”",
        keyEquivalent: "M",
        onSelect: showOpDiv
    }, {
        type: "separator"
    }, {
        label: "生成样式",
        keyEquivalent: "P",
        onSelect: showSaveDiv
    }, {
        label: "样式预览",
        shiftKey: true,
        keyEquivalent: "P",
        onSelect: view_css
    }]
}, {
    label: "帮助",
    items: [{
        label: "关于...",
        name: "about",
        onSelect: menuOpenWin
    }, {
        label: "快捷键...",
        name: "help",
        onSelect: menuOpenWin
    }, {
        type: "separator"
    }, {
        label: "检查更新...",
        onSelect: checkUpdates
    }]
}]
